# Define the stages of the pipeline
stages:
  - build
  - test

# Job to set up the environment and install dependencies
build:
  stage: build
  image: python:3.10
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

# Job to run the tests
test:
  stage: test
  image: python:3.10
  script:
    - source venv/bin/activate
    - pip install -r requirements.txt  # Ensure dependencies are installed
    - python -m unittest discover -s tests
  only:
    - main  # Run tests only on the main branch
